### ISSUE TITLE
Daily Commits for Christmas Coding Challenge

### ISSUE THREAD

**Issue by arzucaner** [yagmuraksu/WWCode-London-Christmas-Coding-Challenge-2023#1]
According to the rules of the Christmas Coding Challenge, let's make sure to send a commit every day for the remaining days. Happy coding! 🎄✨

**Comment by yagmuraksu** [comment]
Sorry for that, I'm gonna be careful next time 👍

**Comment by arzucaner** [comment]
Thank you, everything is perfect!
